#!/bin/sh

if [ -z "$1" ]
then
    from=`git describe --tags $(git rev-list --tags --max-count=1)`
else
    from="$1"
fi

entries=`git log "$from"..HEAD --pretty=%an:%s --first-parent`

echo "Changes:"
echo "$entries" | cut -d: -f2- | sed "s/\(.*\)/    \1/"
echo
echo "Contributors to this release:"
echo "$entries" | cut -d: -f1 | sort | uniq | sed "s/\(.*\)/    \1/"
